version: "3.0"

services:
  db:
    image: postgres:15-alpine3.17
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    restart: always
    ports:
      - 5432:5432

  api:
    build:
      context: .
      dockerfile: ${PWD}/.docker/python/Dockerfile
      target: prod
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ~/logs:/logs

volumes:
  db_volume:
